services:
  promotudo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: promotudo
    volumes:
      - ./app:/app
    networks:
      - promotudo-network
    ports:
      - "9000:9000"

  promotudo-nginx:
    image: nginx:1.25
    container_name: promotudo-nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - promotudo
    networks:
      - promotudo-network

  promotudo-db:
    image: mariadb:11
    container_name: promotudo-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: promotudo
      MYSQL_USER: promotudo
      MYSQL_PASSWORD: promotudo
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - promotudo-network

  promotudo-pma:
    image: phpmyadmin:latest
    container_name: promotudo-pma
    restart: always
    environment:
      PMA_HOST: promotudo-db
      PMA_USER: promotudo
      PMA_PASSWORD: promotudo
      PMA_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - promotudo-db
    networks:
      - promotudo-network

networks:
  promotudo-network:
    driver: bridge

volumes:
  mariadb-data:

